import "../styles/globals.css";
import { Toaster } from 'react-hot-toast';
import ClientOnlyInit from "./client-only-init";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientOnlyInit />
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 2000,
            style: {
              background: '#333',
              color: '#fff',
            },
          }}
        />
      </body>
    </html>
  );
}
